### ISSUE TITLE
Patch `required_deposit` is not charged in prologue but refunded/minted in epilogue

### ISSUE THREAD

**Issue by andyjsbell** [movementlabsxyz/aptos-core#56]
https://github.com/movementlabsxyz/aptos-core//blob/e27151f32165462507aaeccb52b5ddfb98224834/aptos-move/framework/src/natives/function_info.rs#L118
Fix:
https://github.com/aptos-labs/aptos-core/commit/037f163507f80731123bba93ff7faf847cc5d713#diff-7caf9d7232cb5422076b55a1f4ce7c3484b70ab5bc343256402ab033fe0d6e05

**Comment by mzabaluev** [comment]
> Fix: [aptos-labs@037f163#diff-7caf9d7232cb5422076b55a1f4ce7c3484b70ab5bc343256402ab033fe0d6e05](https://github.com/aptos-labs/aptos-core/commit/037f163507f80731123bba93ff7faf847cc5d713#diff-7caf9d7232cb5422076b55a1f4ce7c3484b70ab5bc343256402ab033fe0d6e05)

The referred commit is already an ancestor of the `movement` branch, which is currently used in development and deployment.
