### ISSUE TITLE
[Dev Portal] - Faucet issue: FaucetClientError when using movement init --profile <name>

### ISSUE THREAD

**Issue by 0xBoji** [movementlabsxyz/aptos-core#59]
## Issue description
When I trynna init a profile in testnet but get below error:
```
vboxuser@mylinx:~/aptos-core/aptos-ball$ movement init --profile gamev1
Configuring for profile gamev1
Choose network from [devnet, testnet, local, custom | defaults to devnet]
testnet
Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]

No key given, generating key...
Account 0xdffb62c29f4408331545d38b451432c0ec379551b61f7964b3ebd8d9046af96e doesn't exist, creating it and funding it with 100000000 Octas
{
  "Error": "API error: Faucet issue: FaucetClientError { inner: Inner { kind: HttpStatus(403), source: None } }"
}
```
## Context for reproduction

I only get this when init wallet in testnet!

**Comment by andygolay** [comment]
@l-monninger @mzabaluev do we have a plan to fix this? 

@Rahat-ch mentioned it as well. 

The implication is that `movement init` doesn't work on testnet due to the 403 error. 

Even after mainnet release, I'm guessing devs will still want to initialize with CLI.

**Comment by 0xBoji** [comment]
**maybe we have to --skip-faucet and using another faucet or withdraw from another wallet**

**Comment by andygolay** [comment]
Yep. I've made a PR to fix it so it suggests `--skip-faucet` if that flag is not used, and it links to the faucet UI at https://faucet.movementlabs.xyz after successful `init`. Working on getting it approved now.
